### ISSUE TITLE
Mounting rdflib-endpoint on existing FastAPI app

### ISSUE THREAD

**Issue by cthoyt** [vemonet/rdflib-endpoint#7]
In my service, I already have a FastAPI app instantiated (called `app`). Can you document how to mount the as if it were a `fastapi.APIRouter` so I can do  something like `app.include_router(rdflib_endpoint_router)`?

**Comment by vemonet** [comment]
@cthoyt the new 0.4.0 release introduces a new class `SparqlRouter` to create the SPARQL endpoint as an `APIRouter` instead of a complete `FastAPI`
The new class constructor takes the same arguments as `SparqlEndpoint`, apart from `enable_cors` which needs be enabled at the API level

It is documented in the [README.md](https://github.com/vemonet/rdflib-endpoint#%EF%B8%8F-deploy-as-a-router-to-include-in-an-existing-api)
